# Generated by Django 5.2 on 2025-04-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_end_date',
        ),
    ]
